PhotoShr/Models/favorite.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public int id { get; set; }
        public int photo_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> fav_datetime { get; set; }
    
        public virtual photo photo { get; set; }
        public virtual user user { get; set; }
    }
}

PhotoShr/Models/group.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.group_members = new HashSet<group_members>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> collection_id { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual ICollection<group_members> group_members { get; set; }
    }
}

PhotoShr/Models/set.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class set
    {
        public int set_id { get; set; }
        public int collection_id { get; set; }
    
        public virtual collection collection { get; set; }
    }
}

PhotoShr/Models/user.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.collections = new HashSet<collection>();
            this.comments = new HashSet<comment>();
            this.followers = new HashSet<follower>();
            this.followers1 = new HashSet<follower>();
            this.group_members = new HashSet<group_members>();
            this.photos = new HashSet<photo>();
            this.user_activity = new HashSet<user_activity>();
            this.favorites = new HashSet<favorite>();
            this.likes = new HashSet<like>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string about { get; set; }
        public string gender { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string profile_photo { get; set; }
        public int membership_id { get; set; }
    
        public virtual ICollection<collection> collections { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<follower> followers { get; set; }
        public virtual ICollection<follower> followers1 { get; set; }
        public virtual ICollection<group_members> group_members { get; set; }
        public virtual membership membership { get; set; }
        public virtual ICollection<photo> photos { get; set; }
        public virtual ICollection<user_activity> user_activity { get; set; }
        public virtual ICollection<favorite> favorites { get; set; }
        public virtual ICollection<like> likes { get; set; }
    }
}

PhotoShr/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoShr.Models;
using System.Transactions;

namespace PhotoShr.Controllers
{
    public class GroupController : BaseController
    {
        private photoshareEntities db = new photoshareEntities();

        //
        // GET: /Group/

        public ViewResult Index()
        {
            var groups = db.groups.Include(g => g.collection);
            return View(groups.ToList());
        }

        /// <summary>
        /// Adds Photos to a group
        /// </summary>
        /// <param name="coll"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PhotoAdd(FormCollection coll)
        {
            string grpId = coll["group_id"].ToString();
            using (TransactionScope scope = new TransactionScope())
            {
                string[] selectedPhotos = coll["photos"].ToString().Split(',');
                if (selectedPhotos.Count() > 0)
                {
                    foreach (var sp in selectedPhotos)
                    {
                        collection_photos cp = new collection_photos
                        {
                            collection_id = Int32.Parse(coll["collection_id"]),
                            photo_id = Int32.Parse(sp)
                        };
                        db.collection_photos.Add(cp);
                        db.SaveChanges();
                    }
                }
                scope.Complete();
            }
            return Redirect(string.Format("/Group/Details/{0}",grpId));
        }
        //
        // GET: /Group/Details/5

        public ActionResult Details(int id, string view)
        {
            var group = db.groups.Find(id);
            ViewBag.Group = group;
            var _user = GetLoggedUser();
            ViewBag.IsMember = false;
            //check if user is a memebr of this group
            if (_user != null)
            {
                var check = (from gm in db.group_members
                             where gm.user_id == _user.id
                             && gm.group_id == id
                             select gm).FirstOrDefault();
                if (check != null)
                {
                    ViewBag.IsMember = true;
                }
            }

            if (string.IsNullOrEmpty(view))
                view = "photos";


            switch (view)
            {
                case "members":
                    var grp_mem = db.group_members.Where(gm => gm.group_id == id);
                    return View("group_members", grp_mem.ToList());
                    
                case "about":
                    return View("group_about", group);
                    
                case "add":
                    if (_user == null)
                    {
                        return RedirectToAction("LogOn", "Account");
                    }
                    var _userPhotos = from p in db.photos
                                      where p.user_id == _user.id
                                      select p;

                    ViewBag.UserPhotos = _userPhotos.ToList();
                    return View("group_add");
                case "join":
                    if (_user == null)
                    {
                        return RedirectToAction("LogOn", "Account");
                    }
                    db.group_members.Add(new group_members
                    {
                        group_id = id,
                        joined_date = DateTime.Now,
                        user_id = _user.id
                    });
                    db.SaveChanges();
                    return RedirectToAction("Details", "Group", new { @id = id });
                    
                case "photos":
                default:
                    var grp_photos = from c in db.collections
                                     join cp in db.collection_photos on c.collection_id equals cp.collection_id
                                     join g in db.groups on c.collection_id equals g.collection_id
                                     where g.id == id
                                     select cp;

                    return View(grp_photos.ToList());
                    
            }
        }

        //
        // GET: /Group/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Group/Create

        [HttpPost]
        public ActionResult Create(group group)
        {
            var _user = GetLoggedUser();
            if (_user == null)
            {
                return RedirectToAction("LogOn", "Account");
            }
            if (ModelState.IsValid)
            {
                using (TransactionScope scope = new TransactionScope())
                {
                    collection coll = new collection
                    {
                        collection_name = group.collection.collection_name,
                        created_by = _user.id,
                        created_date = DateTime.Now
                    };
                    db.collections.Add(coll);
                    db.SaveChanges();

                    group newgroup = new Models.group
                    {
                        collection = coll,
                        description = group.description
                    };
                    db.groups.Add(newgroup);
                    db.SaveChanges();

                    //add the user who created the group as one of the group member
                    group_members gm = new group_members
                    {
                        group = newgroup,
                        user_id = _user.id
                    };
                    db.group_members.Add(gm);
                    db.SaveChanges();

                    scope.Complete();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Could not create new group");
            return View(group);
        }

        //
        // GET: /Group/Edit/5

        public ActionResult Edit(int id)
        {
            group group = db.groups.Find(id);
            ViewBag.collection_id = new SelectList(db.collections, "collection_id", "collection_name", group.collection_id);
            return View(group);
        }

        //
        // POST: /Group/Edit/5

        [HttpPost]
        public ActionResult Edit(group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.collection_id = new SelectList(db.collections, "collection_id", "collection_name", group.collection_id);
            return View(group);
        }

        //
        // GET: /Group/Delete/5

        public ActionResult Delete(int id)
        {
            group group = db.groups.Find(id);
            return View(group);
        }

        //
        // POST: /Group/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            group group = db.groups.Find(id);
            db.groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PhotoShr/Controllers/SetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoShr.Models;
using System.Transactions;

namespace PhotoShr.Controllers
{
    public class SetController : BaseController
    {
        private photoshareEntities db = new photoshareEntities();

        //
        // GET: /Set/

        public ViewResult Index(int id)
        {
            var _set = db.sets.Include(s => s.collection).Where(s=>s.set_id == id).SingleOrDefault();
            return View(_set);
        }

        //
        // GET: /Set/Details/5

        public ViewResult Details(int id)
        {
            set set = db.sets.Find(id);
            return View(set);
        }

        //
        // GET: /Set/Create

        public ActionResult Create()
        {
            var _user = this.GetLoggedUser();
            if (_user == null)
            {
                return RedirectToAction("LogOn", "Account");
            }
            var _userPhotos = from p in db.photos
                              where p.user_id == _user.id
                              select p;

            ViewBag.UserPhotos = _userPhotos.ToList();
            return View();
        }

        //
        // POST: /Set/Create

        [HttpPost]        
        public ActionResult Create(FormCollection sForm)
        {
            var _user = GetLoggedUser();
            if (_user == null)
            {
                return Redirect("~/Account/LogOn/");
            }
            ViewBag.User = _user;
            try
            {
                using (TransactionScope scope = new TransactionScope())
                {
                    //create a record in collection
                    //create a record in set
                    //create a record in collection_photos
                    collection _setCollection = new collection
                    {
                        collection_name = sForm["title"],
                        created_by = _user.id,
                        created_date = DateTime.Now
                    };
                    db.collections.Add(_setCollection);
                    db.SaveChanges();

                    set _set = new set();
                    _set.collection = _setCollection;
                    db.sets.Add(_set);
                    db.SaveChanges();

                    if (sForm["photos"] != null)
                    {
                        string[] AllPhotos = sForm["photos"].ToString().Split(',');
                        foreach (var p in AllPhotos)
                        {
                            collection_photos cp = new collection_photos
                            {
                                collection = _setCollection,
                                photo_id = Int32.Parse(p)
                            };
                            db.collection_photos.Add(cp);
                            db.SaveChanges();
                        }
                    }
                    scope.Complete();
                }
                var _userPhotos = from p in db.photos
                                  where p.user_id == _user.id
                                  select p;

                ViewBag.UserPhotos = _userPhotos.ToList();
                // TODO: Add insert logic here

                return Redirect(string.Format("/User/{0}/Sets",Session["LoggedInUser"].ToString()));
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Set/Edit/5

        public ActionResult Edit(int id)
        {
            set set = db.sets.Find(id);
            ViewBag.collection_id = new SelectList(db.collections, "collection_id", "collection_name", set.collection_id);
            return View(set);
        }

        //
        // POST: /Set/Edit/5

        [HttpPost]
        public ActionResult Edit(set set)
        {
            if (ModelState.IsValid)
            {
                db.Entry(set).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.collection_id = new SelectList(db.collections, "collection_id", "collection_name", set.collection_id);
            return View(set);
        }

        //
        // GET: /Set/Delete/5

        public ActionResult Delete(int id)
        {
            set set = db.sets.Find(id);
            return View(set);
        }

        //
        // POST: /Set/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            set set = db.sets.Find(id);
            db.sets.Remove(set);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PhotoShr/Views/User/ChangePassword.cshtml
@model PhotoShr.Models.ChangePasswordModel
@{
    ViewBag.Title = "Change Password";
}

<h1>Change Password</h1>

<p>
    Use the form below to change your password. 
</p>
<p>
    New passwords are required to be a minimum of 6 characters in length.
</p>
<hr />
@section ExtraScripts {
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Password change was unsuccessful. Please correct the errors and try again.")
    <div>

        <div class="editor-label">
            @Html.LabelFor(m => m.OldPassword)
        </div>
        <div class="editor-field">
            @Html.PasswordFor(m => m.OldPassword)
            @Html.ValidationMessageFor(m => m.OldPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.NewPassword)
        </div>
        <div class="editor-field">
            @Html.PasswordFor(m => m.NewPassword)
            @Html.ValidationMessageFor(m => m.NewPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.ConfirmPassword)
        </div>
        <div class="editor-field">
            @Html.PasswordFor(m => m.ConfirmPassword)
            @Html.ValidationMessageFor(m => m.ConfirmPassword)
        </div>

        <p>
            <input type="submit" value="Change Password" class="btn btn-danger" />
        </p>

    </div>
}

PhotoShr/Views/User/Create.cshtml
@model PhotoShr.Models.user

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>user</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.first_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.first_name)
            @Html.ValidationMessageFor(model => model.first_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.last_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.last_name)
            @Html.ValidationMessageFor(model => model.last_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.about)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.about)
            @Html.ValidationMessageFor(model => model.about)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.gender)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.gender)
            @Html.ValidationMessageFor(model => model.gender)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.city)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.city)
            @Html.ValidationMessageFor(model => model.city)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.country)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.country)
            @Html.ValidationMessageFor(model => model.country)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.profile_photo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.profile_photo)
            @Html.ValidationMessageFor(model => model.profile_photo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.is_contact)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.is_contact)
            @Html.ValidationMessageFor(model => model.is_contact)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.membership_id, "membership")
        </div>
        <div class="editor-field">
            @Html.DropDownList("membership_id", String.Empty)
            @Html.ValidationMessageFor(model => model.membership_id)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PhotoShr/Views/User/Delete.cshtml
@model PhotoShr.Models.user

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>user</legend>

    <div class="display-label">first_name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.first_name)
    </div>

    <div class="display-label">last_name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.last_name)
    </div>

    <div class="display-label">about</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.about)
    </div>

    <div class="display-label">gender</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.gender)
    </div>

    <div class="display-label">city</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.city)
    </div>

    <div class="display-label">country</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.country)
    </div>

    <div class="display-label">profile_photo</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.profile_photo)
    </div>

    <div class="display-label">is_contact</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.is_contact)
    </div>

    <div class="display-label">membership</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.membership.username)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PhotoShr/Views/User/Details.cshtml
@model PhotoShr.Models.user

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>user</legend>

    <div class="display-label">first_name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.first_name)
    </div>

    <div class="display-label">last_name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.last_name)
    </div>

    <div class="display-label">about</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.about)
    </div>

    <div class="display-label">gender</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.gender)
    </div>

    <div class="display-label">city</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.city)
    </div>

    <div class="display-label">country</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.country)
    </div>

    <div class="display-label">profile_photo</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.profile_photo)
    </div>

    <div class="display-label">is_contact</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.is_contact)
    </div>

    <div class="display-label">membership</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.membership.username)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PhotoShr/Views/User/Edit.cshtml
@model PhotoShr.Models.user

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>user</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.first_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.first_name)
            @Html.ValidationMessageFor(model => model.first_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.last_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.last_name)
            @Html.ValidationMessageFor(model => model.last_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.about)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.about)
            @Html.ValidationMessageFor(model => model.about)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.gender)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.gender)
            @Html.ValidationMessageFor(model => model.gender)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.city)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.city)
            @Html.ValidationMessageFor(model => model.city)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.country)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.country)
            @Html.ValidationMessageFor(model => model.country)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.profile_photo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.profile_photo)
            @Html.ValidationMessageFor(model => model.profile_photo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.is_contact)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.is_contact)
            @Html.ValidationMessageFor(model => model.is_contact)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.membership_id, "membership")
        </div>
        <div class="editor-field">
            @Html.DropDownList("membership_id", String.Empty)
            @Html.ValidationMessageFor(model => model.membership_id)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PhotoShr/Views/User/Follow.cshtml
@{
    Layout = null;
}
@ViewBag.Msg

PhotoShr/Views/User/Sets.cshtml
@model IEnumerable<PhotoShr.Models.set>
@{
    ViewBag.Title = "photo sets";
}

<h1>@ViewBag.Username - Sets</h1>
<hr />

<ul class="nav nav-pills">
    <li><a href="@Url.Content(string.Format("/User/{0}/Index/", ViewBag.Username))">Photos</a></li>
    <li><a href="@Url.Content(string.Format("/User/{0}/Stories/", ViewBag.Username))">Stories</a></li>
    <li class="active"><a href="@Url.Content(string.Format("/User/{0}/Sets/", ViewBag.Username))">Sets</a></li>
    <li><a href="@Url.Content(string.Format("/User/{0}/Groups/", ViewBag.Username))">Groups</a></li>
    <li><a href="@Url.Content(string.Format("/User/{0}/Favorites/", ViewBag.Username))">Favorites</a></li>
    <li><a href="@Url.Content(string.Format("/User/{0}/RecentActivity/", ViewBag.Username))">Recent Activity</a></li>    
    <li class="pull-right">@Html.ActionLink("Create a new Set", "Create", "Set", null, new { @class = "btn" })</li>
</ul>
<div class="row-fluid">
    <div class="span12">
        @if (Model.Count() > 0)
        {
            <ul class="thumbnails">
                @foreach (var userSet in Model)
                {
                    <li class="span3 thumbnail">
                        @foreach (var pic in userSet.collection.collection_photos.Skip(0).Take(1))
                        {   
                         
                            <a href="@Url.Content(string.Format("/Set/Index/{0}",userSet.set_id))">
                                <img src="@Url.Content(pic.photo.photo_url_m)"  style="width: 260px; height: 180px;" alt="@pic.photo.name" />
                            </a>
                            <div class="caption">
                                <h3>@userSet.collection.collection_name</h3>
                                <hr />
                                <p>@userSet.collection.collection_photos.Count() photos</p>
                            </div>
                         
                        }
                    </li>
                }
            </ul>
        }
        else
        {
            <div class="alert alert-block alert-error fade in">
                <h4 class="alert-heading">You have not created any sets</h4>
            </div>
        
        }

    </div>
</div>