PhotoShr/Models/comment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.story_comments = new HashSet<story_comments>();
            this.photo_comments = new HashSet<photo_comments>();
        }
    
        public int comment_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime comment_datetime { get; set; }
        public string comment_text { get; set; }
    
        public virtual ICollection<story_comments> story_comments { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<photo_comments> photo_comments { get; set; }
    }
}

PhotoShr/Models/like.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class like
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int photo_id { get; set; }
        public Nullable<System.DateTime> like_datetime { get; set; }
    
        public virtual photo photo { get; set; }
        public virtual user user { get; set; }
    }
}

PhotoShr/Models/photo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoShr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo
    {
        public photo()
        {
            this.exif_data = new HashSet<exif_data>();
            this.photo_comments = new HashSet<photo_comments>();
            this.user_activity = new HashSet<user_activity>();
            this.favorites = new HashSet<favorite>();
            this.collection_photos = new HashSet<collection_photos>();
            this.likes = new HashSet<like>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime uploaded_date { get; set; }
        public int user_id { get; set; }
        public string photo_url_o { get; set; }
        public string photo_url_m { get; set; }
        public string photo_url_s { get; set; }
        public int photo_category { get; set; }
        public string tags { get; set; }
        public Nullable<int> views_count { get; set; }
        public Nullable<int> likes_count { get; set; }
        public Nullable<int> comments_count { get; set; }
        public Nullable<int> favs_count { get; set; }
        public Nullable<float> popularity { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<exif_data> exif_data { get; set; }
        public virtual ICollection<photo_comments> photo_comments { get; set; }
        public virtual ICollection<user_activity> user_activity { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<favorite> favorites { get; set; }
        public virtual ICollection<collection_photos> collection_photos { get; set; }
        public virtual ICollection<like> likes { get; set; }
    }
}

PhotoShr/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoShr.Models;
using System.IO;
using System.Transactions;
using PagedList;
using System.Data.Entity.Validation;
using System.Diagnostics;
using MySql.Data.MySqlClient;

namespace PhotoShr.Controllers
{
    public class PhotoController : BaseController
    {
        private photoshareEntities db = new photoshareEntities();


        /// <summary>
        /// Displays upload view
        /// </summary>
        /// <returns></returns>
        public ViewResult Upload()
        {
            //SELECT category_id,category_name from category;
            ViewBag.photo_category = new SelectList(db.categories, "category_id", "category_name", 1);
            return View();
        }

        /// <summary>
        /// handles photo upload 
        /// </summary>
        /// <param name="photo">The photo which is to be uploaded</param>
        /// <returns>returns view</returns>
        [HttpPost]
        public ActionResult Upload(photo photo)
        {
            if (ModelState.IsValid)
            {
                //only members can upload so check if user logged in else redirect to login page
                var loggedUser = GetLoggedUser();
                if (loggedUser == null)
                {
                    return RedirectToAction("LogOn", "Account");
                }

                //get the uploaded file
                HttpPostedFileBase file = Request.Files[0] as HttpPostedFileBase;
                
                //check if the length of file > 0 i.e. its not a empty file
                if (file.ContentLength > 0)
                {
                    
                    var fileName = Path.GetFileNameWithoutExtension(file.FileName); //just filename
                    var fileExt = Path.GetExtension(file.FileName); // file extension
                    
                    var destinationDirectory = Path.Combine(Server.MapPath("~/Images/Uploads/"), loggedUser.id.ToString()); //where the image is going to be uploaded
                    var newFileTemp = loggedUser.id.ToString() + "_" + DateTime.Now.ToString("yyyyMMddHHmmssfff"); // filename format 
                    var newFileName = newFileTemp + "_L" + fileExt; //append the size L(large);M(Medium);S(Small) to the filename
                    var path = Path.Combine(destinationDirectory, newFileName);
                    try
                    {
                        //start transaction
                        using (TransactionScope scope = new TransactionScope())
                        {
                            //if the directory does not exist create it  
                            if (!Directory.Exists(destinationDirectory))
                            {
                                Directory.CreateDirectory(destinationDirectory);
                            }
                            // now save the file to the path
                            file.SaveAs(path);

                            //get the exif data of the image
                            //thanks to http://www.goheer.com for this simple utility
                            exif_data exifData = GetImageExifData(path);

                            //create medium thumbnail
                            var thumbMedium = newFileTemp + "_M" + fileExt;
                            CreateThumbnail(path, ImageSize.Medium, Path.Combine(destinationDirectory, thumbMedium));
                            
                            //create small thumbnail
                            var thumbSmall = newFileTemp + "_S" + fileExt;
                            CreateThumbnail(path, ImageSize.Small, Path.Combine(destinationDirectory, thumbSmall));

                            //save this photo to the data
                            /*
                             *INSERT INTO `photoshare`.`photos`(`name`,`description`,`uploaded_date`,`user_id`,`photo_url_o`,`photo_url_m`,`photo_url_s`,`photo_category`,`tags`,`views_count`,`likes_count`)
                                VALUES(?,?,?,?,?,?,?,?,?,?,?);
                             */
                            photo.photo_url_o = Url.Content("~/Images/Uploads/" + loggedUser.id.ToString() + "/" + newFileName);
                            photo.photo_url_m = Url.Content("~/Images/Uploads/" + loggedUser.id.ToString() + "/" + thumbMedium);
                            photo.photo_url_s = Url.Content("~/Images/Uploads/" + loggedUser.id.ToString() + "/" + thumbSmall);
                            photo.user_id = loggedUser.id;
                            photo.views_count = 0;
                            photo.likes_count = 0;
                            photo.popularity = 0;
                            photo.comments_count = 0;
                            photo.favs_count = 0;
                            db.photos.Add(photo);
                            db.SaveChanges();

                            //save to exif_data
                            /**
                             * INSERT INTO `photoshare`.`exif_data`(`photo_id`,`camera`,`aperture`,`shutter_speed`,`iso`,`date_taken`,`focal_length`)VALUES(?,?,?,?,?,?,?);
                             */
                                exifData.photo = photo;
                                db.exif_data.Add(exifData);
                                db.SaveChanges();

                            //everything went well complete the transaction
                            scope.Complete();
                        }
                        return RedirectToAction("Index", "User");
                    }
                    catch
                    {
                        //something bad has heppened. delete the original file if it was saved
                        FileInfo _file = new FileInfo(path);
                        if (_file.Exists)
                        {
                            _file.Delete();
                        }
                    }

                }
                else
                {
                    ModelState.AddModelError("", "Please select a valid file");
                }
            }

            ViewBag.photo_category = new SelectList(db.categories, "category_id", "category_name", photo.photo_category);
            return View(photo);
        }

        /// <summary>
        /// Reads the exif data of the image
        /// </summary>
        /// <param name="file">The image file</param>
        /// <returns>exif_data object</returns>
        private exif_data GetImageExifData(string file)
        {
            Goheer.EXIF.EXIFextractor exif = new Goheer.EXIF.EXIFextractor(file, "", "");
            exif_data exifData = new exif_data();
            try
            {  

                foreach (System.Web.UI.Pair s in exif)
                {
                    switch (s.First.ToString().ToLower())
                    {
                        case "aperture":
                            exifData.aperture = s.Second.ToString();
                            break;
                        case "f-number":
                            exifData.aperture = s.Second.ToString();
                            break;
                        case "shutter speed":
                            exifData.shutter_speed = s.Second.ToString();
                            break;
                        case "equip model":
                            exifData.camera = s.Second.ToString();
                            break;
                        case "iso speed":
                            exifData.iso = s.Second.ToString();
                            break;
                        case "date time":
                            exifData.date_taken = s.Second.ToString();
                            break;
                        case "focallength":
                            exifData.focal_length = s.Second.ToString();
                            break;
                        default:
                            break;
                    }
                }
                
            }
            catch
            {
            }
            return exifData;
        }

        
        //
        // GET: /Photo/
        //20 items at a time


        /// <summary>
        /// Gets the photos by votes count
        /// </summary>
        /// <param name="category">filter by category</param>
        /// <param name="page">pagenumber</param>
        /// <returns></returns>
        public ViewResult Index(string category = "All Categories", int page = 1)
        {
            if (string.IsNullOrEmpty(category))
                category = "All Categories";
            ViewBag.Category = category;
            //SELECT * FROM category
            ViewBag.Categories = new SelectList(db.categories, "category_name", "category_name", "All Categories");

            if (category.Equals("All Categories") || string.IsNullOrEmpty(category))
            {
                //SELECT * FROM photos order by likes_count,views_count DESC LIMIT page,pageSize
                var photos = db.photos.OrderByDescending(p => p.popularity).ThenByDescending(p=>p.uploaded_date);
                var paginatedPhotos = photos.ToPagedList(page, pageSize);
                return View(paginatedPhotos);
            }
            else
            {
                //SELECT * FROM photos WHERE category_id=category order by likes_count,views_count DESC LIMIT page,pageSize
                var photos = db.photos.Where(p => p.category.category_name == category).OrderByDescending(p => p.popularity).ThenByDescending(p => p.uploaded_date);
                var paginatedPhotos = photos.ToPagedList(page, pageSize);
                return View(paginatedPhotos);
            }
        }

        /// <summary>
        /// Gets the most recent photos
        /// </summary>
        /// <param name="category">filter by category</param>

PhotoShr/Views/Photo/Comment.cshtml
@model PhotoShr.Models.comment
@using PhotoShr.Models
@{
    Layout = null;
    var user = (user)ViewBag.User;
    var failedMsg = "FAILED";
    }
@if (Model != null)
{
    <div class="media">
        <a class="pull-left" href="#">
            @if (@user.profile_photo != null)
            {
                <img src="@Url.Content(@user.profile_photo)" />
            }
            else
            {
                <img src="@Url.Content("~/Images/user_profile.png")" />
            }
        </a>
        <div class="media-body">
            <h4 class="media-heading">

                <a href="@Url.Content(string.Format("/User/{0}/Index", @user.membership.username))">@user.membership.username</a>

                <span style="font-size: small">@Model.comment_datetime</span>
            </h4>
            @Model.comment_text
        </div>
    </div>
} else {
    @failedMsg
}

PhotoShr/Views/Photo/Delete.cshtml
@model PhotoShr.Models.photo
@{
    ViewBag.Title = "Delete photo";
}
<h1>Delete</h1>
<hr />
<p>
    Are you sure you want to delete this photo?
    <ul>
        <li>Photo will be deleted from all the collections (sets, stories, groups)</li>
        <li>Photo will be delete from favorite list of other users</li>
    </ul>
</p>
<div class="row">
    <div class="span9">
        <img src="@Url.Content(@Model.photo_url_o)" alt="@Model.name" />
    </div>
    <div class="span3 plan">
        @using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" class="btn btn-large btn-danger" />
    </p>
}

    </div>
</div>

PhotoShr/Views/Photo/Fav.cshtml
@{
    Layout = null;
}
@ViewBag.Msg

PhotoShr/Views/Photo/Following.cshtml
@model PagedList.IPagedList<PhotoShr.Models.photo>
@{
    ViewBag.Title = "Photos from your friends";
}

@section ExtraScripts  {
    <script>
        $(function () {
            $('#category').change(function () {
                var url = $('#categoryForm').attr("action") + $('#category').val();
                window.location.href = url;
            });
        });
    </script>
}

<ul class="nav nav-pills">
    <li><a href="@Url.Content(string.Format("/Photo/Index/{0}/{1}", ViewBag.Category, 1))">Popular</a></li>
    <li><a href="@Url.Content(string.Format("/Photo/Recent/{0}/{1}", ViewBag.Category, 1))">Recent</a></li>
    <li class="active"><a href="@Url.Content(string.Format("/Photo/Following/{0}/{1}", ViewBag.Category, 1))">Following</a></li>
    <li class="pull-right">
        <form method="get" id="categoryForm" action="@Url.Content("/Photo/Following/")">
            @Html.DropDownList("category", (SelectList)ViewBag.Categories, "All Categories")
        </form>
    </li>
</ul>
<div class="row-fluid">
    <div class="span12">
        @if (Model.Count() > 0)
        {
            <ul class="thumbnails">
                @foreach (var picture in Model)
                { 
                    <li class="span3 photo">
                        <a href="@Url.Content(string.Format("/Photo/Details/{0}", picture.id))" class="thumbnail">
                            <img src="@Url.Content(picture.photo_url_s)"  style="width: 260px; height: 180px;" alt="@picture.name" />
                             <div class="caption">
                                <blockquote>
                                    <p>@picture.name</p>
                                    <small>@picture.user.membership.username</small>                                    
                                </blockquote>
                            </div>
                        </a>

                    </li>
                }
            </ul>
            
        }
        else
        {
            
            <div class="alert alert-block alert-error fade in">
                <h4 class="alert-heading">You are at the end of the page</h4>
                <p>Upload more pictures to get started</p>
                <p>
                    <a class="btn btn-danger" href="@Url.Action("Upload", "Photo")">Upload</a>
                </p>
            </div>
        }

        <div class="pagination">
            <ul>
                @{
                    if (Model.HasPreviousPage)
                    {
                    <li><span><a href="@Url.Content(string.Format("/Photo/Following/{0}/{1}", Html.Encode(ViewBag.Category), 1))">&lt;&lt;</a></span></li>
                    }
                    else
                    {
                    <li><span class="disabled">&lt;&lt;</span></li>
                    }

                    double pageCount = Model.TotalItemCount / Model.PageSize;
                    int pages = (Int32)Math.Ceiling(pageCount);
                    var isEven = pageCount % Model.PageCount;
                    if (isEven > 0)
                    {
                        pages += 1;
                    }

                    for (int p = 1; p <= pages; p++)
                    {
                        if (Model.PageNumber == p)
                        {
                    <li class="active">
                        <a href="@Url.Content(string.Format("/Photo/Following/{0}/{1}", Html.Encode(ViewBag.Category), p))">@p.ToString()</a></li>
                        }
                        else
                        {
                    <li>
                        <a href="@Url.Content(string.Format("/Photo/Following/{0}/{1}", Html.Encode(ViewBag.Category), p))">@p.ToString()</a>
                    </li>
                        }
                    }
                    if (Model.HasNextPage)
                    {
                    <li><span>
                        <a href="@Url.Content(string.Format("/Photo/Following/{0}/{1}", Html.Encode(ViewBag.Category), pages.ToString()))">&gt;&gt;</a></span></li>
                    }
                    else
                    {
                    <li><span class="disabled">&gt;&gt;</span></li>
                    }
                }
            </ul>
        </div>
    </div>
</div>

PhotoShr/Views/Photo/Index.cshtml
@model PagedList.IPagedList<PhotoShr.Models.photo>
@{
    ViewBag.Title = "Index";
}

@section ExtraScripts  {

    <script>
        $(function () {
            $('#category').change(function () {
                var url = $('#categoryForm').attr("action") + $('#category').val();
                window.location.href = url;
            });
        });
    </script>

}

<ul class="nav nav-pills">
    <li class="active"><a href="@Url.Content(string.Format("/Photo/Index/{0}/{1}", ViewBag.Category, 1))">Popular</a></li>
    <li><a href="@Url.Content(string.Format("/Photo/Recent/{0}/{1}", ViewBag.Category, 1))">Recent</a></li>
    <li><a href="@Url.Content(string.Format("/Photo/Following/{0}/{1}", ViewBag.Category, 1))">Following</a></li>
    <li class="pull-right">
        <form method="get" id="categoryForm" action="@Url.Content("/Photo/Index/")">
            @Html.DropDownList("category", (SelectList)ViewBag.Categories, "All Categories")
        </form>
    </li>
</ul>

<div class="row-fluid">
    <div class="span12">
        @if (Model.Count() > 0)
        {
            <ul class="thumbnails">
                @foreach (var picture in Model)
                { 
                    <li class="span3 photo">
                        <a href="@Url.Content(string.Format("/Photo/Details/{0}", picture.id))" class="thumbnail">
                            <img src="@Url.Content(picture.photo_url_m)"  style="width: 260px; height: 180px;" alt="@picture.name" />

                            <div class="caption">
                                <blockquote>
                                    <p>@picture.name</p>
                                    <small>@picture.user.membership.username</small>                                    
                                </blockquote>
                            </div>
                        </a>
                    </li>
                }
            </ul>
            
        }
        else
        {
            
            <div class="alert alert-block alert-error fade in">
                <h4 class="alert-heading">You are at the end of the page</h4>
                <p>Upload more pictures to get started</p>
                <p>
                    <a class="btn btn-danger" href="@Url.Action("Upload", "Photo")">Upload</a>
                </p>
            </div>
        }
        <hr />        
        <div class="pagination">
            <ul>
                @{
                    if (Model.HasPreviousPage)
                    {
                    <li><span><a href="@Url.Content(string.Format("/Photo/Index/{0}/{1}", Html.Encode(ViewBag.Category), 1))">&lt;&lt;</a></span></li>
                    }
                    else
                    {
                    <li><span class="disabled">&lt;&lt;</span></li>
                    }

                    double pageCount = Model.TotalItemCount / Model.PageSize;
                    int pages = (Int32)Math.Ceiling(pageCount);
                    var isEven = pageCount % Model.PageCount;
                    if(isEven > 0) {
                        pages += 1;
                    }
                        
                    for (int p = 1; p <= pages; p++)
                    {
                        if (Model.PageNumber == p)
                        {
                    <li class="active">
                        <a href="@Url.Content(string.Format("/Photo/Index/{0}/{1}", Html.Encode(ViewBag.Category), p))">@p.ToString()</a></li>
                        }
                        else
                        {
                    <li>
                        <a href="@Url.Content(string.Format("/Photo/Index/{0}/{1}", Html.Encode(ViewBag.Category), p))">@p.ToString()</a>
                    </li>
                        }
                    }
                    if (Model.HasNextPage)
                    {
                    <li><span>
                        <a href="@Url.Content(string.Format("/Photo/Index/{0}/{1}", Html.Encode(ViewBag.Category), pages.ToString()))">&gt;&gt;</a></span></li>
                    }
                    else
                    {
                    <li><span class="disabled">&gt;&gt;</span></li>
                    }
                }
            </ul>
        </div>
    </div>
</div>

PhotoShr/Views/Photo/Like.cshtml
@{
    Layout = null;
}
@ViewBag.Msg

PhotoShr/Views/Photo/Recent.cshtml
@model PagedList.IPagedList<PhotoShr.Models.photo>
@{
    ViewBag.Title = "Recently added photos";
}

@section ExtraScripts  {
     <script>
         $(function () {
             $('#category').change(function () {
                 var url = $('#categoryForm').attr("action") + $('#category').val();
                 window.location.href = url;
             });
         });
    </script>
}

<ul class="nav nav-pills">
    <li><a href="@Url.Content(string.Format("/Photo/Index/{0}/{1}",ViewBag.Category,1))">Popular</a></li>
    <li class="active"><a href="@Url.Content(string.Format("/Photo/Recent/{0}/{1}",ViewBag.Category,1))">Recent</a></li>
    <li><a href="@Url.Content(string.Format("/Photo/Following/{0}/{1}",ViewBag.Category,1))">Following</a></li>
    <li class="pull-right">
        <form method="get" id="categoryForm" action="@Url.Content("/Photo/Recent/")">
            @Html.DropDownList("category", (SelectList)ViewBag.Categories, "All Categories")
        </form>
    </li>
</ul>
<div class="row-fluid">
    <div class="span12">
        @if (Model.Count() > 0)
        {
            <ul class="thumbnails">
                @foreach (var picture in Model)
                { 
                    <li class="span3 photo">
                        <a href="@Url.Content(string.Format("/Photo/Details/{0}", picture.id))" class="thumbnail">
                            <img src="@Url.Content(picture.photo_url_s)"  style="width: 260px; height: 180px;" alt="@picture.name" />
                             <div class="caption">
                                <blockquote>
                                    <p>@picture.name</p>
                                    <small>@picture.user.membership.username</small>                                    
                                </blockquote>
                            </div>
                        </a>

                    </li>
                }
            </ul>
            
        }
        else
        {
            
            <div class="alert alert-block alert-error fade in">
                <h4 class="alert-heading">You are at the end of the page</h4>
                <p>Upload more pictures to get started</p>
                <p>
                    <a class="btn btn-danger" href="@Url.Action("Upload", "Photo")">Upload</a>
                </p>
            </div>
        }

       <div class="pagination">
            <ul>
                @{
                    if (Model.HasPreviousPage)
                    {
                    <li><span><a href="@Url.Content(string.Format("/Photo/Recent/{0}/{1}",Html.Encode(ViewBag.Category),1))">&lt;&lt;</a></span></li>
                    }
                    else
                    {
                    <li><span class="disabled">&lt;&lt;</span></li>
                    }

                    double pageCount = Model.TotalItemCount / Model.PageSize;                    
                    int pages = (Int32)Math.Ceiling(pageCount);
                    var isEven = pageCount % Model.PageCount;
                    if (isEven > 0)
                    {
                        pages += 1;
                    }

                    for (int p = 1; p <= pages; p++)
                    {
                        if (Model.PageNumber == p)
                        {
                    <li class="active">
                        <a href="@Url.Content(string.Format("/Photo/Recent/{0}/{1}",Html.Encode(ViewBag.Category),p))">@p.ToString()</a></li>
                        }
                        else
                        {
                    <li>
                        <a href="@Url.Content(string.Format("/Photo/Recent/{0}/{1}",Html.Encode(ViewBag.Category),p))">@p.ToString()</a>
                    </li>
                        }
                    }
                    if (Model.HasNextPage)
                    {
                    <li><span>
                        <a href="@Url.Content(string.Format("/Photo/Recent/{0}/{1}",Html.Encode(ViewBag.Category),pages.ToString()))">&gt;&gt;</a></span></li>
                    }
                    else
                    {
                    <li><span class="disabled">&gt;&gt;</span></li>
                    }
                }
            </ul>
        </div>
    </div>
</div>

PhotoShr/Views/Photo/Upload.cshtml
@model PhotoShr.Models.photo
@{
    ViewBag.Title = "Upload picture";
}
@section ExtraStyles {
    <link href="@Url.Content("~/Styles/uploader.css")" rel="stylesheet" />
}

@section ExtraScripts {
    <script src="@Url.Content("~/Scripts/uploader.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}


<h1>Upload</h1>
<hr />
<h3>Choose file(s)</h3>

@using (Html.BeginForm("Upload", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p>
        <input id="files-upload" name="files-upload" type="file">
    </p>
    <table style="border: 0px;">
        <tr>
            <td>
                <div id="file-list">
                </div>
            </td>
        </tr>
        <tr>
            <td id="file-metadata" style="display: none; vertical-align: top; padding-left: 10px;">
                <fieldset>
                        <legend>Details</legend>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.name, "Title")
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.name)
                        @Html.ValidationMessageFor(model => model.name)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.description, "Description")
                    </div>
                    <div class="editor-field">
                        @Html.TextAreaFor(model => model.description)
                        @Html.ValidationMessageFor(model => model.description)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.photo_category, "Category")
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("photo_category", ViewBag.photo_category as SelectList)
                        @Html.ValidationMessageFor(model => model.photo_category)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.tags, "Tags")
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.tags)
                        @Html.ValidationMessageFor(model => model.tags)
                    </div>

                    <div class="actions">
                        <input type="submit" value="Save" class="btn primary">
                    </div>
                </fieldset>
            </td>
        </tr>
    </table>
}